local SKIN = {
	--meta
	Author = "Cryotheum",
	DermaVersion = 1,
	PrintName = "Player Expressive Canvas Skin",
	
	--fonts
	fontCategoryHeader =	"TabLarge",
	fontFrame =				"DermaDefault",
	fontTab =				"DermaDefault",
	
	--colors
	bg_alt1 =						Color(50, 50, 50),
	bg_alt2 =						Color(55, 55, 55),
	bg_color =						Color(101, 100, 105, 255),
	bg_color_sleep =				Color(70, 70, 70, 255),
	bg_color_dark =					Color(55, 57, 61, 255),
	bg_color_bright =				Color(220, 220, 220, 255),
	colButtonBorder =				Color(20, 20, 20),
	colButtonBorderHighlight =		Color(255, 255, 255, 50),
	colButtonBorderShadow =			Color(0, 0, 0, 100),
	colButtonText =					Color(255, 255, 255),
	colButtonTextDisabled =			Color(255, 255, 255, 55),
	colCategoryText =				Color(255, 255, 255),
	colCategoryTextInactive =		Color(200, 200, 200),
	colCollapsibleCategory =		Color(255, 255, 255, 20),
	colMenuBG =						Color(255, 255, 255, 200),
	colMenuBorder =					Color(0, 0, 0, 200),
	colNumberWangBG =				Color(255, 240, 150),
	colPropertySheet =				Color(170, 170, 170),
	colTab =						Color(170, 170, 170),
	colTabInactive =				Color(140, 140, 140),
	colTabShadow =					Color(0, 0, 0, 170),
	colTabText =					Color(255, 255, 255),
	colTabTextInactive =			Color(0, 0, 0, 200),
	colTextEntryBG =				Color(240, 240, 240),
	colTextEntryBorder =			Color(20, 20, 20),
	colTextEntryText =				Color(20, 20, 20),
	colTextEntryTextHighlight =		Color(20, 200, 250),
	colTextEntryTextCursor =		Color(0, 0, 100, 255),
	colTextEntryTextPlaceholder =	Color(128, 128, 128),
	combobox_selected =				Color(100, 170, 220),
	control_color =					Color(120, 120, 120),
	control_color_highlight =		Color(150, 150, 150),
	control_color_active =			Color(110, 150, 250),
	control_color_bright =			Color(255, 200, 100),
	control_color_dark =			Color(100, 100, 100),
	frame_border =					Color(50, 50, 50, 255),
	listview_hover =				Color(70, 70, 70),
	listview_selected =				Color(100, 170, 220),
	panel_transback =				Color(255, 255, 255, 50),
	text_bright =					Color(255, 255, 255),
	text_normal =					Color(180, 180, 180),
	text_dark =						Color(20, 20, 20),
	text_highlight =				Color(255, 20, 20),
	tooltip =						Color(255, 245, 175),
	
	
	texGradientUp =					Material("gui/gradient_up"),
	texGradientDown =				Material("gui/gradient_down"),
	
	--paint functions generated by gwen
	tex = {
		
	}
}
